In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import numpy as np 
import pandas as pd 

In [3]:
data= pd.read_csv("R_text.csv")
data.shape
print(data)

     Temperature (K)       1/T     ln(T)   ln(k(T))      Ln(k)
0          314.62800  0.003178 -5.751391 -10.239262  10.239262
1          314.64308  0.003178 -5.751439  -9.720674   9.720674
2          314.64978  0.003178 -5.751460  -9.355756   9.355756
3          314.66132  0.003178 -5.751497  -9.051082   9.051082
4          314.67325  0.003178 -5.751535  -8.874602   8.874602
..               ...       ...       ...        ...        ...
743        466.88150  0.002142 -6.146075  -8.776876   8.776876
744        466.96640  0.002141 -6.146257  -9.014906   9.014906
745        467.05040  0.002141 -6.146437  -9.312094   9.312094
746        467.13610  0.002141 -6.146621  -9.830538   9.830538
747        467.21980  0.002140 -6.146800 -10.599651  10.599651

[748 rows x 5 columns]


In [4]:
A_Matrix= np.array(data.loc[:,'Ln(k)'])
A_matrix= A_Matrix.reshape(-1,1)
print(f' the A= \n {A_matrix}')
print(A_matrix.shape)


 the A= 
 [[10.23926181]
 [ 9.72067366]
 [ 9.35575612]
 [ 9.05108209]
 [ 8.87460193]
 [ 8.88140672]
 [ 8.84025311]
 [ 8.86758058]
 [ 9.00467511]
 [ 9.0467973 ]
 [ 9.16754081]
 [ 9.17011984]
 [ 9.28235224]
 [ 9.25534293]
 [ 9.23032013]
 [ 9.15408544]
 [ 9.04973657]
 [ 8.94453355]
 [ 8.84992741]
 [ 8.7542656 ]
 [ 8.64976185]
 [ 8.56996278]
 [ 8.54077818]
 [ 8.55774206]
 [ 8.47062576]
 [ 8.34206222]
 [ 8.23935566]
 [ 8.21477341]
 [ 8.13893622]
 [ 8.03219785]
 [ 7.8829447 ]
 [ 7.82530865]
 [ 7.77764831]
 [ 7.7584163 ]
 [ 7.73111903]
 [ 7.70215186]
 [ 7.69593833]
 [ 7.6910076 ]
 [ 7.68706184]
 [ 7.71523803]
 [ 7.74196834]
 [ 7.73511274]
 [ 7.75632052]
 [ 7.73931847]
 [ 7.72678624]
 [ 7.70026489]
 [ 7.68029409]
 [ 7.65881344]
 [ 7.6545121 ]
 [ 7.64802003]
 [ 7.62552199]
 [ 7.60886699]
 [ 7.59051212]
 [ 7.59121621]
 [ 7.59011804]
 [ 7.59743373]
 [ 7.60443214]
 [ 7.61681291]
 [ 7.62295946]
 [ 7.60817901]
 [ 7.61240031]
 [ 7.63210395]
 [ 7.65235337]
 [ 7.69340751]
 [ 7.71078283]
 [ 7.73433223]


In [5]:
B_Matrix= np.array(data.loc[:, ['ln(T)','1/T']])
ones_column = np.ones((A_matrix.shape[0], 1))
B_matrix= np.hstack((ones_column, B_Matrix))
print(f"B: \n {B_matrix}")
B_T= B_matrix.T
B_T_B= np.matmul(B_matrix.T,B_matrix)
B_T_B_inv= np.linalg.inv(B_T_B)
B_T_A= np.matmul(B_T, A_matrix)
try:
    X_matrix= np.matmul(B_T_B_inv,B_T_A)
    print(f"\n X is \n {X_matrix}")
except np.linalg.LinAlgError:
    print("Matrix is singulard cannot an be inverted.")

B: 
 [[ 1.00000000e+00 -5.75139099e+00  3.17835700e-03]
 [ 1.00000000e+00 -5.75143892e+00  3.17820400e-03]
 [ 1.00000000e+00 -5.75146021e+00  3.17813700e-03]
 ...
 [ 1.00000000e+00 -6.14643717e+00  2.14109700e-03]
 [ 1.00000000e+00 -6.14662065e+00  2.14070400e-03]
 [ 1.00000000e+00 -6.14679981e+00  2.14032000e-03]]

 X is 
 [[   441.70692262]
 [    61.6476858 ]
 [-24871.96264518]]


In [6]:
# B * X = A 
try:
    X= np.linalg.lstsq(B_matrix, A_matrix, rcond=None)
    print(X)
except np.linalg.LinAlgError as e:
    # Handles singular or non-square matrices
    print("Error:", e)

(array([[   441.706923  ],
       [    61.64768586],
       [-24871.96266508]]), array([651.7358846]), np.int32(3), array([1.63033610e+02, 3.93841444e-01, 3.39150047e-04]))


In [7]:
def solve_sliding_3rows(B,a):
    solution = []
    for i in range(B.shape[0]-2):
        A= B[i:i+3,:]
        re_a= a[i: i+3,]   
        x= np.linalg.solve(A, re_a)
        solution.append(x)
    return np.array(solution)

X_matrix = solve_sliding_3rows(B_matrix, A_matrix)
X_matrix

array([[[ 3.02889909e+06],
        [ 4.50518699e+05],
        [-1.37737726e+08]],

       [[ 4.39149891e+06],
        [ 6.52040854e+05],
        [-2.01785678e+08]],

       [[-3.09186296e+06],
        [-4.56985881e+05],
        [ 1.45851549e+08]],

       ...,

       [[ 4.93177166e+06],
        [ 6.89840249e+05],
        [-3.23059905e+08]],

       [[ 1.16875535e+07],
        [ 1.63513572e+06],
        [-7.64694582e+08]],

       [[ 1.67117506e+07],
        [ 2.33821155e+06],
        [-1.09293081e+09]]])

In [8]:
def m_values(matrix):
    matrix=[]
    for j in range(len(X_matrix)):
        for i in range(len(X_matrix[j])):
            if (i == 1):
                matrix.append(X_matrix[j][i])
                print(f'x_matrix[{j},{i}]= {X_matrix[j][i]}')
            else:
                print("")
    return np.array(matrix)
m= m_values(X_matrix)
print(m.shape)


x_matrix[0,1]= [450518.69935741]


x_matrix[1,1]= [652040.85437568]


x_matrix[2,1]= [-456985.88058261]


x_matrix[3,1]= [635699.1531305]


x_matrix[4,1]= [210756.89812493]


x_matrix[5,1]= [887078.58346988]


x_matrix[6,1]= [549661.9014079]


x_matrix[7,1]= [609786.48425585]


x_matrix[8,1]= [-282405.05711296]


x_matrix[9,1]= [-365209.16726997]


x_matrix[10,1]= [1342484.92803933]


x_matrix[11,1]= [511664.3674982]


x_matrix[12,1]= [10044.25185726]


x_matrix[13,1]= [113080.94396126]


x_matrix[14,1]= [-7186.38694731]


x_matrix[15,1]= [289699.1929654]


x_matrix[16,1]= [-80115.02131883]


x_matrix[17,1]= [-111470.19450921]


x_matrix[18,1]= [-34044.02398923]


x_matrix[19,1]= [-185128.91390475]


x_matrix[20,1]= [-946450.44597393]


x_matrix[21,1]= [255655.58594196]


x_matrix[22,1]= [569749.01176507]


x_matrix[23,1]= [364934.76989881]


x_matrix[24,1]= [180034.81886286]


x_matrix[25,1]= [2034192.32753411]


x_matrix[26,1]= [178714.23789259]


x_matrix[27,1]= [5806.21067382]


x